name: Build Android

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip build]') }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.2"
          channel: 'stable'
          cache: true
          cache-key: flutter

      - name: Flutter clear pub cache
        run: flutter pub cache repair

      - name: Install Flutter dependencies
        run: flutter pub get

      - run: flutter clean

      - name: Analyze files
        run: flutter analyze .

      - run: |
          flutter build apk 
